# https://docs.percy.io/v1/docs/configuration
version: 1
snapshot:
  # by default take visual snapshots on the desktop resolution
  # but we can overwrite it from individual snapshots
  widths: [1280]
  min-height: 1024
